---
global:
  resolve_timeout: 1m

route:
  receiver: 'telegram_drm_it'
  group_by: ['instance', 'alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  routes:
    - matchers:
        - severity="critical"
      receiver: 'telegram_drm_it'
      repeat_interval: 30m
    - matchers:
        - severity="warning"
      receiver: 'telegram_drm_it'
      repeat_interval: 2h

receivers:
  - name: 'telegram_drm_it'
    telegram_configs:
      - bot_token: '8171004718:AAFuuuB8Tk1cqPvf6S6OEqr3sIu37RwiAI0'
        chat_id: 1296546071
        message: |
          {{ if eq .Status "firing" }}🚨{{ else }}✅{{ end }} *{{ .Status | toUpper }}: {{ .GroupLabels.alertname }}*

          {{ range .Alerts }}
          📍 *Device*: {{ .Labels.instance }}
          ⚠️ *Severity*: {{ .Labels.severity }}
          📝 *Info*: {{ .Annotations.description }}
          {{ end }}
        parse_mode: 'Markdown'

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal: ['instance']
