---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

rule_files:
  - "/etc/prometheus/alert.rules"

scrape_configs:

  - job_name: 'Real_Videotron'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://100.125.1.96:8080
          - http://100.114.121.89:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  - job_name: 'Consul_Videotron'
    metrics_path: /probe
    params:
      module: [http_2xx]
    consul_sd_configs:
      - server: 'consul:8500'
        services: ['videotron']
    relabel_configs:
      - source_labels:
          - __meta_consul_service_address
          - __meta_consul_service_port
        separator: ':'
        target_label: __param_target
        replacement: 'http://$1'
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
      - source_labels: [__meta_consul_node]
        target_label: node
      - source_labels: [__meta_consul_tags]
        regex: ',(.*),'
        target_label: vtron_name
        replacement: '$1'
