# Linux devices (commented out, uncomment jika ada device Linux baru)
#[videotron_linux]
#vtron-01 ansible_host=100.86.201.107 ansible_user=turna vtron_name="Videotron Tunjungan Plaza" ansible_become_password=turna
#vtron-02 ansible_host=100.73.98.9 ansible_user=vtron2 vtron_name="Videotron Galaxy Mall" ansible_become_password=vtron2

[videotron]
vtron-03 ansible_host=100.125.1.96 ansible_user="vtron3" ansible_become_password=vtron3 vtron_name="Videotron Pakuwon Mall" ansible_connection=winrm ansible_winrm_transport=basic ansible_port=5985 ansible_winrm_server_cert_validation=ignore
vtron-04 ansible_host=100.118.6.22 ansible_user="vtron4" ansible_become_password=vtron4 vtron_name="Videotron Royal Plaza" ansible_connection=winrm ansible_winrm_transport=basic ansible_port=5985 ansible_winrm_server_cert_validation=ignore

[monitoring_server]
monitor-local ansible_host=127.0.0.1 ansible_connection=local

[all:vars]
ansible_python_interpreter=/usr/bin/python3
monitoring_server_ip=127.0.0.1
monitoring_server_tailscale_ip=100.80.162.115
github_username=lockturna