---
- name: Setup Monitoring Server
  hosts: monitoring_server
  become: true
  roles:
    - monitoring_server

- name: Setup Windows Videotron
  hosts: videotron
  become: false
  roles:
    - rdp_setup
    - consul_agent_windows
    - content_delivery